import type { Metadata } from "next";

/**
 * The site's canonical origin. Everything absolute (canonical URLs, sitemap,
 * Open Graph images, JSON-LD) resolves from here, so the apex domain is the
 * one version of every page Google indexes.
 *
 * Override with NEXT_PUBLIC_SITE_URL for staging; no trailing slash.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://jural.app").replace(/\/$/, "");

/** Only production should be indexed; previews and staging stay out of Google. */
export const INDEXABLE = SITE_URL === "https://jural.app";

export const SITE_NAME = "Jural";

/** Homepage title and description, and the defaults for any page without its own. */
export const SITE_TITLE = "Jural: AI Legal CRM for Solo Attorneys and Small Law Firms";
export const SITE_DESCRIPTION =
  "Run your law practice by talking to it. Jural is a private, AI-native legal CRM for iPhone and Mac: intake, drafting, e-signatures and billing in one thread.";

/** Public, indexable routes. Add a page here when it ships. */
export const ROUTES = [
  { path: "/", priority: 1 },
  { path: "/product/iphone", priority: 0.9 },
  { path: "/product/mac", priority: 0.9 },
  { path: "/security", priority: 0.8 },
  { path: "/demo", priority: 0.7 },
  { path: "/about", priority: 0.6 },
] as const;

/**
 * Metadata for one page. Canonical and Open Graph are set per page on purpose:
 * set in the root layout they would be inherited, and every page would declare
 * the homepage as its canonical.
 */
export function pageMetadata({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  path: string;
}): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    // Named explicitly: a page that sets its own openGraph no longer inherits
    // the image generated by app/opengraph-image.tsx.
    openGraph: {
      title,
      description,
      url: path,
      siteName: SITE_NAME,
      type: "website",
      locale: "en_US",
      images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: title }],
    },
    twitter: { card: "summary_large_image", title, description, images: ["/opengraph-image"] },
  };
}
